### ISSUE TITLE
stylelint - should it target ALL css files?

### ISSUE THREAD

**Issue by joesnellpdx** [10up/10up-toolkit#121]
Currently, all `*.css` files are linted with `10up-toolkit` regardless if an `entry` or not - unlike with javascript. _Should_ this be how we lint `.css` files, or should it be more directly tied to our `entry` points? We can, for reference, add a `.stylintignore` file if needed as an alternative, but I want to be sure we are on the same page with the current setup.

For reference, we were working on a migration to `10up-toolkit` with css issues all over the place and couldn't manage debugging by turning off / on entry points. We had to use a `stylelintignore` file to handle it. It worked, but it _felt_ like `entries` should have worked. 

CC: @nicholasio @devinle @fabiankaegy

**Comment by nicholasio** [comment]
@joesnellpdx The way our eslint is setup is to lint all js/ts files regardless of entry points. So when you run `10up-toolkit lint-style` it will lint all CSS files. The same happens when you run `10up-toolkit lint-js`.

For cases where the team decides to ignore certain files during migration, I feel like it should be manually added to `.stylelintignore` or manually specify which directories to lint in the lint-style command.

However, if you're talking about linting during webpack compilation I agree that it should only lint the files that are being compiled. Are you saying that stylelint is linting files that are not being compiled by 10up-toolkit as part of `10up-toolkit build/watch?`

**Comment by joesnellpdx** [comment]
@nicholasio 

Sorry, you are correct. I'm concerned with `watch` here. Unless I'm doing something wrong, it is targeting all `.css` files on `watch`.... which may not be a big deal or noticeable when we are typically watching all our css files... debugging it can be a pain.

I can work around with the `stylelintignore` file for now, but something we should consider (and be sure I'm not crazy) in the future.

**Comment by tlovett1** [comment]
I lost of few hours debugging why Stylelint was hanging. I ended up figuring out it was processing old CSS files that weren't included in Webpack entry points. I 100% think this should only lint files you are targeting.

**Comment by nicholasio** [comment]
https://github.com/10up/10up-toolkit/pull/146 "fixes" this by using an option called "lintDiryModulesOnly". I've added to both stylelint and eslint for consistency.

This does not change the lining comments, just how eslint and stylelint run within webpack.
