### ISSUE TITLE
Replace `imagemin-webpack-plugin` with `image-webpack-loader`

### ISSUE THREAD

**Issue by felipeelia** [10up/10up-toolkit#131]
### Is your enhancement related to a problem? Please describe.

Currently, the project relies on [imagemin-webpack-plugin](https://github.com/Klathmon/imagemin-webpack-plugin), a package that didn't have any release since February 2019. Due to a series of dependencies that starts with this package, 10up toolkit is dependent on old and insecure versions of other packages. Although so far that only led to false positives, it may bring some serious problems in the (near) future.

According to [this page](https://www.npmtrends.com/image-webpack-loader-vs-imagemin-webpack-plugin-vs-img-loader), a good candidate would be [image-webpack-loader](https://github.com/tcoopman/image-webpack-loader), a package that seems to be actively maintained.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rdimascio** [comment]
#129 can be addressed here as well

**Comment by nicholasio** [comment]
I'm fine with the approach of moving to `image-webpack-loader`. We need to make sure it works well with webpack 5 asset resources as the file-loader is deprecated in webpack 5

**Comment by jeffpaul** [comment]
@felipeelia @rdimascio @nicholasio could https://www.npmjs.com/package/image-minimizer-webpack-plugin also be of use here?  We're in need of resolving a replacement for `imagemin-webpack-plugin` as it has a multi-level-deep dependency with a security issue that's been flagged by users of the Sophi plugin (which uses 10up-toolkit) and since `imagemin-webpack-plugin` is no longer maintained we really need to pick a replacement and move on to close out this issue.  Looking for at least some consent on the best path forward so this can get resolved.

**Comment by rdimascio** [comment]
@jeffpaul @nicholasio @felipeelia I think that is the best solution, as it looks like `imagemin-webpack-plugin` is being deprecated in favor of `image-minimizer-webpack-plugin` — https://github.com/webpack-contrib/image-minimizer-webpack-plugin/issues/225#issuecomment-881373737

**Comment by nicholasio** [comment]
The imagemin-webpack-loader won't work for our needs so [image-minimizer-webpack-plugin](https://www.npmjs.com/package/image-minimizer-webpack-plugin) seems like the best path forward.
