### ISSUE TITLE
After upgrading to v3 an out of memory error was thrown on Circle CI

### ISSUE THREAD

**Issue by orballo** [10up/10up-toolkit#167]
### Describe the bug

While building a package in Circle CI (VIP) it threw the following error:

```
 > component-library@1.3.11 build
 > ../../../node_modules/.bin/10up-toolkit build -f=commonjs
 node:internal/event_target:777
   process.nextTick(() => { throw err; });
                            ^
 RangeError [Error]: WebAssembly.instantiate(): Out of memory: wasm memory
 Emitted 'error' event on Worker instance at:
     at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
     at Worker.[kOnMessage] (node:internal/worker:300:37)
     at MessagePort.<anonymous> (node:internal/worker:201:57)
     at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
     at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```
Our current fix was downgrading to v2.1.0, which got rid of the error.

This issue didn't happen while running the command locally. My guess is that it is leaking memory somewhere and Circle CI has a limited amount of memory available, therefore only in that environment the error is present.

### Steps to Reproduce

1. Try to build a package in Circle CI with 10up-toolkit v3.0.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
This seems to be an issue with squosh which is wasm based https://github.com/GoogleChromeLabs/squoosh. Which node version are you using?

One thing you could try is disabling image optimization

```javascript
// webpack.config.js
const config = require('10up-toolkit/config/webpack.config.js');

delete config.optimization.minimizer[1]; // or  config.optimization.minimizer[1] = false;

config.optimization.minimizer = config.optimization.minimizer.filter(Boolean);

module.exports = config;
```

UPDATE: Confirmed that the above config works in CircleCI and gets rid of the error. The actual issue seems to be with Node.js and some of the limitations of Circle CI. Note: This removes the optimizations for static images referenced in the code and copied to the dist folder.

**Comment by orballo** [comment]
I implemented this fix and it works now. Closing the issue.
