### ISSUE TITLE
Toolkit still shows IE11 related warnings in the console and HMR overlay

### ISSUE THREAD

**Issue by fabiankaegy** [10up/10up-toolkit#196]
### Describe the bug

Even after updating 10up-toolkit to version 4.0.0 it still shows console warnings and more importantly blocking HMR overlay warnings for autoprefixer IE11 issues. 

<img width="1439" alt="CleanShot 2022-05-11 at 07 55 36@2x" src="https://user-images.githubusercontent.com/20684594/167778706-d0c336c4-5a62-458b-9398-6bc5b1eb3c3a.png">

<img width="1439" alt="" src="https://user-images.githubusercontent.com/20684594/167794288-7653a094-48d5-4044-b009-14876ede60a1.png">

### Steps to Reproduce

use something like `align-items` on a grid element in css to see the warning

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Antonio-Laguna** [comment]
@fabiankaegy not actually a bug but rather autoprefixer warning you of pitfalls when translating grid syntax into IE mode. See https://github.com/postcss/autoprefixer#does-autoprefixer-polyfill-grid-layout-for-ie

For the time being you can provide your `postcss.config.js` file with something like this:

```js
const baseConfig = require('10up-toolkit/config/postcss.config.js');
const path = require('path');

module.exports = (props) => {
	const config = baseConfig(props);
	config.plugins['postcss-preset-env'].autoprefixer.grid = false;	

	return config;
};
```

Which should get rid of your warnings.

@nicholasio I agree this is not ideal and we've seen recurring comments internally. Perhaps we should follow Autoprefixer and make it opt-in rather than forcing it in as seen here https://github.com/10up/10up-toolkit/blob/develop/packages/toolkit/config/postcss.config.js#L11

Let me know if a PR would be helpful. This would technically be a breaking change but given the impact I wouldn't really go that far. I don't think anyone is relying on Grid Autoprefixing for IE on Version 4.0.0

**Comment by fabiankaegy** [comment]
@Antonio-Laguna The reason why I flagged it as a bug is, that since HMR is now the default in development mode these warnings are being picked up by the error overlay and therefore prevent any development from happening till they are fixed. Which is not great. Especially since we are no longer supporting IE 11 and therefore can use more modern syntax.

<img width="1728" alt="CleanShot 2022-05-11 at 09 34 33@2x" src="https://user-images.githubusercontent.com/20684594/167794288-7653a094-48d5-4044-b009-14876ede60a1.png">

**Comment by Antonio-Laguna** [comment]
@fabiankaegy lacked the context completely! Apologies! That's indeed obnoxious. Let me know if the config does help!

**Comment by fabiankaegy** [comment]
Yeah no worries I should have added that screenshot in the original ticket description 🤦

**Comment by fabiankaegy** [comment]
>```js
>const baseConfig = require('10up-toolkit/config/postcss.config.js');
>
>module.exports = (props) => {
>	const config = baseConfig(props);
>	config.plugins['postcss-preset-env'].autoprefixer.grid = false;	
>
>	return config;
>};
>```

@Antonio-Laguna This works like a charm 🚀

**Comment by willhowat** [comment]
@fabiankaegy @Antonio-Laguna thanks for raising this it was on my TODO list.
Just as a thumbs up from me, I've also just implemented the postcss config fix on one project and it seems to be fine.

**Comment by nicholasio** [comment]
@Antonio-Laguna I think we should just disable the autoprofexir thing for grids. Since we're not oficially supporting IE 11 I don't think we need to treat this as a breaking change. A PR would be great!
