### ISSUE TITLE
editor-style.css vs. Scaffold theme editor-style-overrides.css

### ISSUE THREAD

**Issue by bjorn2404** [10up/10up-toolkit#367]
https://github.com/10up/10up-toolkit/blob/abc5afb7bb7b5b1ace889b11542ea1539785c54b/packages/toolkit/config/postcss.config.js#L18

There appears to be a naming discrepancy with this file name vs. the name of the file in the Scaffold's example theme via this commit: https://github.com/10up/wp-scaffold/commit/5e044b1ecbd04bba09a4cbd8ed89875709e75768

Maybe the file in the theme shouldn't have been renamed? Or, could this be updated to account for both file names?

**Comment by fabiankaegy** [comment]
Hey @bjorn2404 👋 

The reason this was renamed was specifically because of this. The treatment here is no longer desirable because when yoz add your stylesheet via the `add_editor_styles` function, or via the `enqueue_block_asset` it loads in the editor and gets scoped to the `.editor-styles-wrapper` already. So there is no need for this plugin anymore (in 95% of cases)

**Comment by bjorn2404** [comment]
Thanks, got it. I was doing a manual migration to WP Scaffold for a project and it looks like it was using `enqueue_block_editor_assets` vs. `enqueue_block_assets` for editor styles, which is why the wrapper class wasn't being added.
