### ISSUE TITLE
Build fails with local font files

### ISSUE THREAD

**Issue by rdimascio** [10up/10up-toolkit#38]
**Describe the bug**
Static assets like fonts cannot be resolved from local paths in stylesheets.

When including local font files and referencing them from a stylesheet, the build will fail and throw an error —

```
ERROR in ./assets/css/frontend/style.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '../../assets/fonts/guardian/GuardianTextSans-Regular-Web.eot' in '/Users/ryan/wp-local-docker-sites/blocks-test/wordpress/wp-content/themes/10up-theme/assets/css/frontend'
```

This is resolved by adding `url: false,` to the `css-loader` options.

**Steps to Reproduce**
1. Create a file called `10up.ttf` in the `assets/fonts` folder.
2. Add the following to `assets/css/frontend/global/index.css`:
```css
@font-face {
	font-family: "10up";
	font-style: normal;
	font-weight: 400;
	src: url("../../assets/fonts/10up.ttf") format("ttf")
}

html,
body {
	font-family: "10up", sans-serif;
        font-weight: 400;
}

```
3. Run `npm run build` in the theme directory.

**Expected behavior**
The assets should build without an error.

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by nicholasio** [comment]
THe proposed solution makes sense since we're copying all static assets to the dist foler, disabling URL allows us to reference those files relative to the file. However, I'm wondering if we should use [asset modules](https://github.com/10up/10up-scripts/blob/develop/config/webpack.config.js#L163) instead and stop using `CopyWebpackPlugin`.

We would need a new rule like this:

```
{
       test: /\.{jpg,jpeg,png,gif,svg,eot,ttf,woff,woff2}/,
       type: 'asset/resource'
 }
 ```

Then remove `CopyWebpackPlugin`

This will tell webpack how to resolve URLs in post css (and any other file). Webpack will automatically include the static file in the output folder when required. The main benefit is that we only ever include static assets if they are effectively used.

@rdimascio Mind trying if the above solution works?

**Comment by rdimascio** [comment]
@nicholasio I like the idea of only including files in the output directory that are being used. I was able to get this working with a few modifications. I'll open a PR for this implementation shortly.

**Comment by nicholasio** [comment]
Now I'm wondering if there's any use case for adding assets that are not referenced in CSS and JS but are maybe manually reference somehow in the front end? like a hardcoded img tag? Feels like we should just keep CopyWebPack plugin and disable URL resolution in css-loader

cc @joesnellpdx any thoughts?

**Comment by rdimascio** [comment]
Ah, you're right. There's definitely use case for that. A custom logo is the first thing that comes to mind. A lot of times that is hard coded in partials but not referenced in CSS & JS.

**Comment by joesnellpdx** [comment]
> Now I'm wondering if there's any use case for adding assets that are not referenced in CSS and JS but are maybe manually reference somehow in the front end? like a hardcoded img tag? Feels like we should just keep CopyWebPack plugin and disable URL resolution in css-loader
> 
> cc @joesnellpdx any thoughts?

@nicholasio @rdimascio I agree. There will be use cases where we will access assets directly in the front end. We access svgs this way all the time (site logo) and sometimes use things like hard coded placeholder images. I have not tested this at all due to time, but this is definitely a consideration.

**Comment by nicholasio** [comment]
Makes sense and this was exactly how the old scaffold was handling things.
